/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Country {
  id?: number;
  iso?: string;
  iso3?: string;
  name?: string;
  upperName?: string;
}
