/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerAddressDto {
  addressLine1: string;
  addressLine2?: string;
  city: string;
  country: number;
  id?: string;
  postalCode: string;
}
