/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductQuantityDto } from '../models/product-quantity-dto';
export interface ProductRequestOrderDto {
  address: string;
  products: Array<ProductQuantityDto>;
}
