/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Country } from '../models/country';
export interface SellerDto {
  addressLine1: string;
  addressLine2?: string;
  city?: string;
  company?: string;
  country: Country;
  note?: string;
  phoneNumber: string;
  sellerName: string;
}
