spring:
    application:
        name: RetroBased
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: Sium12
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
    compression:
        enabled: 'true'
    port: '8081'