spring:
  application:
    name: RetroBased
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Sium12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/<NOME REAME>
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  compression:
    enabled: 'true'
  port: '8081'